name: Build and Run AI Code Review By Main Maven Jar
# 当有代码推送到仓库的 main 分支时，这个 Actions 工作流会被触发并执行
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    # 指定了作业运行的环境
    runs-on: windows
    steps:
      - name: Debug Secret
        run: |
          if [ -z "${{ secrets.ACTION_TOKEN }}" ]; then
            echo "ERROR: ACTION_TOKEN is empty or not found!"
            exit 1
          else
            echo "ACTION_TOKEN is set (length: ${#TOKEN})"
          fi
        shell: bash
        env:
          TOKEN: ${{ secrets.ACTION_TOKEN }}
      - name: Checkout repository
        uses: https://gitea.com/actions/checkout@v6
        with:
          fetch-depth: 0
          server-url: http://www.emryscheng.top:3000
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Set up JDK 17
        uses: https://gitea.com/actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        shell: cmd
        run: mvn clean install

      - name: Copy ai-code-review-sdk JAR
        shell: cmd
        run: mvn dependency:copy -Dartifact=io.github.emryscheng:ai-code-review-sdk:1.0 -DoutputDirectory=./libs

      - name: Run code review
        shell: cmd
        run: java -jar ./libs/ai-code-review-sdk-1.0.jar