name: Build and Run AI Code Review By Main Maven Jar
# 当有代码推送到仓库的 main 分支时，这个 Actions 工作流会被触发并执行
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    # 指定了作业运行的环境
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: http://www.emryscheng.top:3000/actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: http://www.emryscheng.top:3000/actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Copy ai-code-review-sdk JAR
        run: mvn dependency:copy -Dartifact=io.github.emryscheng:ai-code-review-sdk:1.0 -DoutputDirectory=./libs

      - name: Run code review
        run: java -jar ./libs/ai-code-review-sdk-1.0.jar